chore(npm): enforcing npm version
ui5-community/wdi5 pull request #174
Opened 2022-03-09 11:58 UTC by dominikfeininger

not bulletproof yet, but happy to get suggestions ;)

2022-03-09 12:30 UTC, vobu requested changes
please also 
- check the code scan findings 
- the linter gh action output

2022-03-09 12:30 UTC, vobu commented on check-versions.js
> +const exec = require("child_process").exec
const { exec, execSync } = require("child_process")

2022-03-09 12:30 UTC, vobu commented on check-versions.js
> +            `updating npm version from ${npmVersion} to the lasted version because required npm version in package.json is set to ${sReqNpmVersion}`
typo: "latest"

2022-03-14 15:28 UTC, dominikfeininger commented
I noticed that the `engine-strict` prevents the execution of the `check-versions` script if the npm version is too low. So I guess we need to decide which way we would like to go.

2022-09-16 12:33 UTC, vobu commented
closing this as obsolete und not relevant any more.
docs point to npm >= 7 → every dev manages to comply ;)

2022-09-16 12:33 UTC, closed without merging