feat: authentication capabilities
ui5-community/wdi5 pull request #369
Opened 2022-11-11 16:14 UTC by vobu

authentication capabilities:
- BTP SAP Cloud IdP
- BTP Standard IdP
- Office 365
- Basic Auth
- custom auth fields

authentication works for single browser scenarios as well as multiremote.

credentials and authentication types are provided at design-time through configuration and don't require code changes.
docs still todo, short version is:
- standard: provide env vars `wdi5_username` and `wdi5_password` w/ respective values
- multiremote: provide env var s`wdi5_$remote-id_username` and `wdi5_$remote-id_password` w/ respective values
- add `wdi5:authentication` config object (see `src/types/wdi5.types.ts` → `*Authenticator`) to the `capabilities` section of the `wdio.conf.(t|j)s` file

2022-11-13 09:05 UTC, monavari-lebrecht approved these changes

2022-11-14 08:13 UTC, Siolto requested changes
throw error when obligatory parameters for custom auth are is missing needs to be implemented.

2022-11-14 08:13 UTC, Siolto commented on src/lib/authentication/CustomAuthenticator.ts
> +        this.usernameSelector = options.usernameSelector ?? "Logger.error()"
fallback is missing

2022-11-14 09:28 UTC, vobu commented on src/lib/authentication/CustomAuthenticator.ts
> +        this.usernameSelector = options.usernameSelector ?? "Logger.error()"
done, thanks for catching this!

2022-11-14 09:35 UTC, merged