feat: add watch support for authentication
ui5-community/wdi5 pull request #372
Opened 2022-11-15 16:36 UTC by monavari-lebrecht

check, whether the browser is already logged in by checking a cookie. If so, the login is skipped

2022-11-15 16:49 UTC, vobu requested changes
mini coding remark - but could you please add a test for each auth case to validate a logged-in state?

2022-11-16 11:44 UTC, monavari-lebrecht commented on src/lib/authentication/Authenticator.ts
> +        const index = cookies.findIndex((item) => {
Prettier converts the short form again to

const index = cookies.findIndex((item) => {
            item.name === "isLoggedIn"
        })
        
and then I dont like the short form that much and imho the additionaln return is better to read

2022-11-16 16:06 UTC, vobu commented on src/lib/authentication/Authenticator.ts
> +        const index = cookies.findIndex((item) => {
👍

2022-11-21 19:14 UTC, vobu approved these changes

2022-11-21 19:15 UTC, merged