docs: authentication, UI5 obj API alignment, wdi5.url deprecation, and more
ui5-community/wdi5 pull request #375
Opened 2022-11-21 21:47 UTC by vobu

2022-11-22 21:08 UTC, Siolto requested changes
just very small remarks. The rest is very well written in my opinion 👍

2022-11-22 21:08 UTC, Siolto commented on docs/recipes.md
> +WebdriverIO has a extensive element [API](https://webdriver.io/docs/api/). The [Element API] specifically can be quite useful to check if the page elements are in a certain state eg. [isDisplayed](ht
```suggestion
WebdriverIO has a extensive element [API](https://webdriver.io/docs/api/). The [Element API] specifically can be quite useful to check if the page elements are in a certain state e.g. [isDisplayed](https://webdriver.io/docs/api/element/isDisplayed) or [isClickable](https://webdriver.io/docs/api/element/isClickable).
```

2022-11-22 21:08 UTC, Siolto commented on docs/usage.md
> +At the same time, the `wdi5`-api can be mixed with `wdio`'s api during tests at will - there is no restriction to use either or. Even a [fluent async transition](ttps://ui5-community.github.io/wdi5/#
```suggestion
At the same time, the `wdi5`-api can be mixed with `wdio`'s api during tests at will - there is no restriction to use either one. Even a [fluent async transition](ttps://ui5-community.github.io/wdi5/#/recipes?id=using-wdio-functions) between the two is possible:
```

2022-11-23 08:03 UTC, dominikfeininger approved these changes

2022-11-23 08:12 UTC, vobu commented on docs/authentication.md
> +}
shortened the example

2022-11-23 13:12 UTC, Siolto approved these changes

2022-11-23 15:29 UTC, merged