Enhance and update the Typescript app
ui5-community/wdi5 pull request #434
Opened 2023-02-24 10:05 UTC by Siolto

- Use latest UI5-Tooling Version
    - no more need of separate `src` and `webapp` folder
    - livetranspilation
- Move App to ODataV4
    - Use ODataV4 Northwind Service
    - Use V4 mockserver and add mockdata 
- Prepare the App for the FlexibleProgrammingModel
   - Make the necessary changes in the component and controllers
   - Adapt `manifest.json`
   - Use `sapui5/ts-types-esm` instead of `openui5/ts-types-esm`
   - Use workaround in the `index.html` for receiving the correct `height`

2023-02-24 10:47 UTC, Siolto commented
@vobu: I have removed node14 for the ts-app tests, as we now require at least node 16

2023-02-27 16:51 UTC, vobu requested changes

2023-02-27 16:51 UTC, vobu commented on examples/ui5-ts-app/ui5.yaml
>    version: "1.106.0"
bump to latest?

2023-02-27 16:51 UTC, vobu commented on examples/ui5-ts-app/ui5.yaml
> +        # annotations:
can be removed -> we're annotating metadata.xml directly

2023-08-24 15:17 UTC, closed without merging