feat: add option to ignore urls for auto waiting
ui5-community/wdi5 pull request #575
Opened 2024-01-10 14:26 UTC by sebbi08

Add the option to skip the XHRWaiter an the fetchWaiter based on an regex in the wdi5 config.

2024-01-11 08:46 UTC, sebbi08 commented
Could you hint me where in the Docs this should be documented ?

2024-01-11 08:59 UTC, Siolto requested changes
Type definition for new optional wdi5 property is missing [here](https://github.com/ui5-community/wdi5/blob/6421e8055ef2cb1789cb421a077ec26659837fe1/src/types/wdi5.types.ts#L26)

Documentation should be added somewhere [here](https://github.com/ui5-community/wdi5/blob/6421e8055ef2cb1789cb421a077ec26659837fe1/docs/configuration.md?plain=1#L24) I guess.

2024-01-11 08:59 UTC, Siolto commented on client-side-js/injectXHRPatch.cjs
> +            function hooketoXHROpen(method, url, async) {
```suggestion
            function hooktoXHROpen(method, url, async) {
```

2024-01-12 09:06 UTC, vobu reviewed
main thing is my naming suggestion (don't hate me, please)

2024-01-12 09:06 UTC, vobu commented on docs/configuration.md
> +Ignore list in form of regex. Those will be used to ignore certain XHR/Fetch call from beeing waited for by the OPA5 Waiters. This can be used in combination with longpolling requests to continusly u
```suggestion
Array of URLs (as strings), either relative or absolute. `RegEx` are supported.   
Querying the URLs will be excluded from the UI5 lifecycle sync. Meaning: no Test code will wait until querying the URLs resolve. 
Typical use case is "longpolling" requests that continuously update your app.
```

2024-01-12 09:06 UTC, vobu commented on docs/configuration.md
> +### `autoWaitUrlIgnoreRegex`
see my rename comment

2024-01-12 09:06 UTC, vobu commented on examples/ui5-js-app/scripts/delayedMockServer.js
> +module.exports = async function middleware(middlewareConfig) {
this is so cool. well well done!!!

2024-01-12 09:06 UTC, vobu commented on examples/ui5-js-app/ui5.yaml
> +    - name: delayed-mockserver
again: cool idea, well done 😀

2024-01-12 09:06 UTC, vobu commented on examples/ui5-js-app/webapp/Component.js
> +                    const startFetch = () => {
i keep my fingers crossed that the gh runners are equipped with enough memory for the CI runs 😁

2024-01-15 07:15 UTC, sebbi08 commented on src/lib/wdi5-bridge.ts
> +    await clientSide_injectXHRPatch(config, browserInstance)
hi sadly not the clientSide_injectTools function add the compare version function to the browser and that is needed in clientSide_injectXHRPatch and checkUI5Version is actualy not async.

2024-01-15 07:18 UTC, sebbi08 commented on src/types/wdi5.types.ts
> +        autoWaitUrlIgnoreRegex?: string[]
haha no hate here :D my naming skills are way to verbal. I am fine with that.

2024-01-15 09:44 UTC, merged